# Generated by Django 2.1.3 on 2018-11-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Office', '0002_auto_20181125_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
